# Define common labels for Docker objects
x-labels: &labels
  labels:
    # Name of the application using COMPOSE_PROJECT_NAME
    app.name: ${COMPOSE_PROJECT_NAME}

# Shared default settings for all services
x-settings: &settings
  # Allow containers to access the host machine using host.docker.internal alias
  extra_hosts:
    - "host.docker.internal:host-gateway"
  # Restart the container unless it was explicitly stopped
  restart: unless-stopped
  # Set init to true to handle zombie processes
  init: true
  # Set the pull policy to pull if not present
  pull_policy: missing
  # Set the default network mode to bridge
  networks:
    default:
      aliases:
        - ${COMPOSE_PROJECT_NAME}-network
      driver: bridge
  # Apply the common labels to all services
  <<: *labels

# Define the default network for the containers to use
networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}-network
    driver: bridge
    attachable: true
    driver_opts:
      com.docker.network.bridge.name: ${COMPOSE_PROJECT_NAME}-bridge
    <<: *labels

# Define named volumes for persistent storage
volumes:
  ui:
    name: ui
    driver: local
  assets:
    name: assets
    driver: local
  keycloak-db:
    name: keycloak-db
    driver: local

services:
  api:
    container_name: api
    hostname: api
    build:
      context: .
      dockerfile: ./services/api/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://api:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    <<: *settings
