version: "3"

tasks:
  hello:
    desc: "Prints hello world"
    cmds:
      - echo "Hello, world!"
    silent: true

  install:devtools:
    desc: "Install dependencies using install-devtools.sh"
    cmds:
      - bash ./scripts/install-devtools.sh
    silent: true

  install:devtools:local:
    desc: "Install dependencies using install-devtools.sh locally in the .cache directory"
    cmds:
      - source ./scripts/install-devtools.sh --local --fresh
    silent: true
