services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - no_proxy=${no_proxy}
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
    environment:
      - http_proxy=
      - https_proxy=
      - no_proxy="*"
      - HTTP_PROXY=
      - HTTPS_PROXY=
      - NO_PROXY="*"
    volumes:
      - ..:/workspace:cached
    networks:
      - devcontainer

networks:
  devcontainer:
    driver: bridge
