services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    networks:
      - devcontainer

networks:
  devcontainer:
    driver: bridge
